FROM tiangolo/uwsgi-nginx:python3.5
MAINTAINER Michael Perez "mpuhrez@paralelstudios.com"

COPY . /app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -e .
